name: "Typical Technological Trickery"
highlighter: pygments
timezone: Europe/London
# encoding: UTF8

# Only use title in urls
permalink: /:title.html

# # url for compsoc
# url: http://compsoc.man.ac.uk/~shep

# url for AWS
url: http://techtrickery.com

# url for testing
# url: http://localhost:4000/

gems:
  - jekyll-feed
