name: "Typical Technological Trickery"
highlighter: pygments
timezone: Europe/London
# encoding: UTF8

# Only use title in urls
permalink: /:title.html

plugins:
  - jekyll-feed

exclude: [Gemfile, Gemfile.lock, README.md, build.sh, preview.sh]
